Add plop generator
FotonTech/NFoTon pull request #77
Opened 2021-06-30 01:16 UTC by joaopaulomoraes

## What is the referred issue?

Issue: #75 

## What does this do?

https://user-images.githubusercontent.com/16243531/123887140-5a7c9c80-d927-11eb-80d3-db9f10eb5264.mp4

## What does it affect?

## Any debts to pay? (optional)

## Review Checklist

- [ ] Added and/or modified tests for affected areas
- [ ] Ready to review
- [ ] Ready to merge

2021-06-30 22:50 UTC, CarmichaelF commented on packages/frontend/generators/templates/index.tsx.hbs
> +import * as S from './styles'
Really good work here, I would just import it as a const instead of default cause the other components/elements are already using this pattern.

2021-06-30 22:51 UTC, CarmichaelF requested changes
I've left some comments but in general is a really good work, thank you for your contribution.

2021-07-01 00:07 UTC, joaopaulomoraes commented on packages/frontend/generators/templates/index.tsx.hbs
> +import * as S from './styles'
Sure, no problem!

2021-07-01 11:35 UTC, CarmichaelF approved these changes
Good to go! Thank you!

2021-07-01 11:35 UTC, merged