Feat/cta
FotonTech/NFoTon pull request #83
Opened 2021-07-15 18:04 UTC by JonathaGomes

## What is the reffered issue?

Issue: #21

## What does this do?

This component is a snippet of [landing page](https://www.figma.com/file/pSuBkbjhzZdq0nvHhDFbk7/crypter?node-id=1376%3A36337)

I had a problem with the font in the storybook, but I think I solved it by adding @import from the fonts to globalStyles.ts

## Review Checklist

- [ ] Added and/or modified tests for affected areas
- [x] Ready to review
- [x] Ready to merge

2021-07-20 15:12 UTC, joaopaulomoraes requested changes

2021-07-20 16:06 UTC, JonathaGomes commented on packages/frontend/src/styles/globalStyles.ts
> +@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&family=Poppins:wght@400;500;600;700&display=swap');
Yes, but the storybook cannot get a font without this @import

2021-07-20 16:06 UTC, JonathaGomes commented on packages/frontend/src/components/Cta/styles.ts
> +  color: #fff;
Thank You

2021-07-20 17:27 UTC, joaopaulomoraes requested changes

2021-07-20 17:27 UTC, joaopaulomoraes commented on packages/frontend/src/styles/globalStyles.ts
> +@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@700&family=Poppins:wght@400;500;600;700&display=swap');
This looks like a storybook issue, I think we can break it down into a new issue.

2021-07-20 17:43 UTC, joaopaulomoraes commented
Thanks @JonathaGomes, nice job!

2021-07-24 13:33 UTC, CarmichaelF approved these changes
Looks like a pretty solid component, thanks for your work here. 👍

2021-07-24 13:33 UTC, merged